sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t chldppwls12/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true chldppwls12/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-ap-northeast-2-289560731340
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
